// Code generated by Embedder. DO NOT EDIT.

package internal

const (
	// Source: resources/Index.html
	Index = `H4sIAAAAAAAC/4SOQW6EMAxF95ziy6t2AYh9yAnaQ6TBQKo0RiS0qqLcvUJ0hpnFaN7Ksq2nlzMG
Hl1gkJWQOCRCXUoFADnjx6UZzZtY4/G/3VFzp3NG884xmolRCpSD9SbGnkYTMZp68vLBNW+rLExa
tU6rdu70xcxh2I3nVN2kfJpvE+3qlkR4HnN8Iv0u3NOXDJtn0tfzjpUQxXPjZXqh+3B6PUXtYXrY
+BcAAP//ZlUC/i0BAAA=`
)
