// +build debug

// Code generated by MockGen. DO NOT EDIT.
// Source: hmac.go

package signature

import (
	ctx "github.com/cjtoolkit/ctx"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockHmacUtil is a mock of HmacUtil interface
type MockHmacUtil struct {
	ctrl     *gomock.Controller
	recorder *MockHmacUtilMockRecorder
}

// MockHmacUtilMockRecorder is the mock recorder for MockHmacUtil
type MockHmacUtilMockRecorder struct {
	mock *MockHmacUtil
}

// NewMockHmacUtil creates a new mock instance
func NewMockHmacUtil(ctrl *gomock.Controller) *MockHmacUtil {
	mock := &MockHmacUtil{ctrl: ctrl}
	mock.recorder = &MockHmacUtilMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHmacUtil) EXPECT() *MockHmacUtilMockRecorder {
	return m.recorder
}

// Sign mocks base method
func (m *MockHmacUtil) Sign(context ctx.Context, message string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", context, message)
	ret0, _ := ret[0].(string)
	return ret0
}

// Sign indicates an expected call of Sign
func (mr *MockHmacUtilMockRecorder) Sign(context, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockHmacUtil)(nil).Sign), context, message)
}

// Check mocks base method
func (m *MockHmacUtil) Check(context ctx.Context, message string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", context, message)
	ret0, _ := ret[0].(string)
	return ret0
}

// Check indicates an expected call of Check
func (mr *MockHmacUtilMockRecorder) Check(context, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockHmacUtil)(nil).Check), context, message)
}
