#!/bin/bash
set -e
cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )
LD="-X 'main.build=$(date -u) $(git rev-parse HEAD)'"
GOOS=linux GOARCH=amd64 go build -v -ldflags="$LD " -o bin/build/site .
asset/taskforce prod
cat asset.zip >> bin/build/site