// +build debug

// Code generated by MockGen. DO NOT EDIT.
// Source: home_view.go

package view

import (
	reflect "reflect"

	ctx "github.com/cjtoolkit/ctx/v2"
	model "github.com/cjtoolkit/ignition/site/homePage/model"
	gomock "github.com/golang/mock/gomock"
)

// MockHomeView is a mock of HomeView interface
type MockHomeView struct {
	ctrl     *gomock.Controller
	recorder *MockHomeViewMockRecorder
}

// MockHomeViewMockRecorder is the mock recorder for MockHomeView
type MockHomeViewMockRecorder struct {
	mock *MockHomeView
}

// NewMockHomeView creates a new mock instance
func NewMockHomeView(ctrl *gomock.Controller) *MockHomeView {
	mock := &MockHomeView{ctrl: ctrl}
	mock.recorder = &MockHomeViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHomeView) EXPECT() *MockHomeViewMockRecorder {
	return m.recorder
}

// ExecIndexView mocks base method
func (m *MockHomeView) ExecIndexView(context ctx.Context, data model.Index) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ExecIndexView", context, data)
}

// ExecIndexView indicates an expected call of ExecIndexView
func (mr *MockHomeViewMockRecorder) ExecIndexView(context, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecIndexView", reflect.TypeOf((*MockHomeView)(nil).ExecIndexView), context, data)
}
