// Code generated by Embedder. DO NOT EDIT.

package internal

const (
	// Source: resources/Flashbag.html
	Flashbag = `H4sIAAAAAAAC/6quVlBJzkksLlawslXQcwazamurqxWKEvPSUxX0fFOLixPTU0GCNimZZQpgtbZK
iTmpRSUKCM21tUp21dUKeiBl+imZZSBOal6KQm0tIAAA//95PI63YQAAAA==`
	// Source: resources/Master.html
	Master = `H4sIAAAAAAAC/2xSwW7UMBC95yuGgSPOCnFBKI6ESpHgAlJbCY5ee7aZ1rGDPZtqFeXfkXezq0VN
LrHfPL+Z9+xpgnc79pQfkr+zcSD4rGGffK6/FRTmuXnz9efN/Z9ft9BJ79uqKT/wJjxqpIAFIOPa
CgCg6UkM2M6kTKJxLzv1Ca9Lncig6O+eR42/1cMXdRP7wQhvPSHYGISCaPx+q8k90n8ng+lJ48j0
MsQkV+QXdtJpRyNbUsfNe+DAwsarbI0n/eEsJCye2mmC+r6sirnNCTvVPYdnSOQ1Zjl4yh2RIHSJ
dhpfBVXfXTiw8GubM8I8rwwuHfWkbPQxXc3+dnf8Fv40wdZH+wxYEkWoYZ6nCSg4UPNcNZtT0M02
ukNbNY5HsN7krLEIGg6UoN+qjxc5ddZbGq5IOh7bqsk28SAgh4E09tHty3XkZNds/zCjWfjYGw71
0+K52Zzgtrrq/HRhrzRfjGyOD+tfAAAA//+kvMdgigIAAA==`
)
