// Code generated by Embedder. DO NOT EDIT.

package internal

const (
	// Source: resources/Flashbag.html
	Flashbag = `H4sIAAAAAAAC/6quVlBJzkksLlawslXQcwazamurqxWKEvPSUxX0fFOLixPTU0GCNimZZQpgtbZK
iTmpRSUKCM21tUp21dUKeiBl+imZZSBOal6KQm0tIAAA//95PI63YQAAAA==`
	// Source: resources/Master.html
	Master = `H4sIAAAAAAAC/2ySQW/UMBCF7/kVw8ARZ4W4IBRHQqVIcAGpVIKj155tpnXsYM+mWln57yjZdLWI
5JLk+fObeWOXAm8O7CnfJ39n40DwUcMx+Vx/mVWYpubV5+83P3//uIVOet9WzfwCb8KDRgo4C2Rc
WwEAND2JAduZlEk0HuWgPuD1UicyKPpz5FHjL3X/Sd3EfjDCe08INgahIBq/3mpyD/TPzmB60jgy
PQ8xyRX8zE467WhkS2r5eQscWNh4la3xpN+9GAmLp7YUWD6gntPtzuIZ8ByeIJHXmOXkKXdEgtAl
Omj8b1L13YWBla9tzgjTtNG5dNSTstHHdNX868PyrHwpsPfRPgHOI8WlwVKAggM1TVWzO0+62Ud3
aqvG8QjWm5w1zoaGAyXo9+r9xU69+K0FNywdj23VZJt4EJDTQBr76I7zeeRkt2J/M6NZeewNh/px
zdzsznJbXVV+vNAbxdcgu+Vm/Q0AAP//WvybZ4sCAAA=`
)
