// +build debug

// Code generated by MockGen. DO NOT EDIT.
// Source: redis.go

package redis

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockRedisCore is a mock of RedisCore interface
type MockRedisCore struct {
	ctrl     *gomock.Controller
	recorder *MockRedisCoreMockRecorder
}

// MockRedisCoreMockRecorder is the mock recorder for MockRedisCore
type MockRedisCoreMockRecorder struct {
	mock *MockRedisCore
}

// NewMockRedisCore creates a new mock instance
func NewMockRedisCore(ctrl *gomock.Controller) *MockRedisCore {
	mock := &MockRedisCore{ctrl: ctrl}
	mock.recorder = &MockRedisCoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRedisCore) EXPECT() *MockRedisCoreMockRecorder {
	return m.recorder
}

// GetBytes mocks base method
func (m *MockRedisCore) GetBytes(key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBytes", key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBytes indicates an expected call of GetBytes
func (mr *MockRedisCoreMockRecorder) GetBytes(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBytes", reflect.TypeOf((*MockRedisCore)(nil).GetBytes), key)
}

// MustGetBytes mocks base method
func (m *MockRedisCore) MustGetBytes(key string) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MustGetBytes", key)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// MustGetBytes indicates an expected call of MustGetBytes
func (mr *MockRedisCoreMockRecorder) MustGetBytes(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustGetBytes", reflect.TypeOf((*MockRedisCore)(nil).MustGetBytes), key)
}

// SetBytes mocks base method
func (m *MockRedisCore) SetBytes(key string, value []byte, expiration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBytes", key, value, expiration)
}

// SetBytes indicates an expected call of SetBytes
func (mr *MockRedisCoreMockRecorder) SetBytes(key, value, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBytes", reflect.TypeOf((*MockRedisCore)(nil).SetBytes), key, value, expiration)
}

// Exist mocks base method
func (m *MockRedisCore) Exist(key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exist", key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exist indicates an expected call of Exist
func (mr *MockRedisCoreMockRecorder) Exist(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exist", reflect.TypeOf((*MockRedisCore)(nil).Exist), key)
}

// Delete mocks base method
func (m *MockRedisCore) Delete(keys ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Delete", varargs...)
}

// Delete indicates an expected call of Delete
func (mr *MockRedisCoreMockRecorder) Delete(keys ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRedisCore)(nil).Delete), keys...)
}
