// Code generated by Embedder. DO NOT EDIT.

package internal

const (
	// Source: resources/Flashbag.html
	Flashbag = `H4sIAAAAAAAC/6quVlBJzkksLlawslXQcwazamurqxWKEvPSUxX0fFOLixPTU0GCNimZZQpgtbZK
iTmpRSUKCM21tUp21dUKeiBl+imZZSBOal6KQm0tIAAA//95PI63YQAAAA==`
	// Source: resources/Master.html
	Master = `H4sIAAAAAAAC/2xSPa/UMBDs8yuWpcWJEA2FHQk9XkEFxUOC0rH3XvzOH8Hey+kU5b+jXHJckC5N
1rPjmdHI8t3X708vv388Q8/Bt5VcfuB1fFVIEReAtG0rAAAZiDWYXudCrPDEB/EZ96ueeRD05+RG
hb/Ezy/iKYVBs+s8IZgUmSIr/PasyL7SfzejDqRwdHQeUuYd+ews98rS6AyJ6+EDuOjYaS+K0Z7U
x5sQO/bUThPUL8sE8yybFVv33sUjZPIKC188lZ6IEfpMB4XNHSrbXJtSHmTkngIJk3zKu5jvD9dv
408TdD6ZI+BSHkIN8zxNQNGCmOdKNmunskv20lbSuhGM16UoXAS1i5QhdOLTPzlx09sMH0haN7aV
LCa7gYEvAykMyZ6W5ks2Cps3Pep13QTtYv1WsJXNirTVzuNOfGCzRW6ur+VvAAAA//+4E9LPPQIA
AA==`
)
