// +build debug

// Code generated by MockGen. DO NOT EDIT.
// Source: show_error.go

package internal

import (
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	reflect "reflect"
)

// MockShowError is a mock of ShowError interface
type MockShowError struct {
	ctrl     *gomock.Controller
	recorder *MockShowErrorMockRecorder
}

// MockShowErrorMockRecorder is the mock recorder for MockShowError
type MockShowErrorMockRecorder struct {
	mock *MockShowError
}

// NewMockShowError creates a new mock instance
func NewMockShowError(ctrl *gomock.Controller) *MockShowError {
	mock := &MockShowError{ctrl: ctrl}
	mock.recorder = &MockShowErrorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockShowError) EXPECT() *MockShowErrorMockRecorder {
	return m.recorder
}

// ShowError mocks base method
func (m *MockShowError) ShowError(req *http.Request, code int, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowError", req, code, message)
}

// ShowError indicates an expected call of ShowError
func (mr *MockShowErrorMockRecorder) ShowError(req, code, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowError", reflect.TypeOf((*MockShowError)(nil).ShowError), req, code, message)
}
