// Code generated by Embedder. DO NOT EDIT.

package internal

const (
	// Source: resources/Error.html
	Error = `H4sIAAAAAAAC/1yOwQrCMAyG7z7Fzx6gsvvoSW8Kgr5A6TJXHO3IIh5C310s25zeEr4vfFFFS12I
hMqnKBSlQs47AGj62qpCggwEg5ybfV/bglTxCtLDnJJ3w3Iwk9AhJoE5Mh+cOHPh1D69hBS3YimM
n8Aqnmma3J1KabR/JtOPexXnHzd2ftaZ7PYHiu0S+27r9A4AAP//Kg/kHPUAAAA=`
)
