// Code generated by Embedder. DO NOT EDIT.

package internal

const (
	// Source: resources/Error.html
	Error = `H4sIAAAAAAAC/1zOwQrCMAwG4LtP8bMHqOw+etKbguBeoHSZK452ZBEPoe8uzFWnt4T/I39U0VEf
IqHyKQpFqZDzDgCaobaqMG2QkZBzsx9quySqeAYZYE7Ju7H4NQk9YhKYI/PBiTMXTt3DS0hxC5eC
ablf4Jnm2d3eTZP9k0w/9irO31t2fuVMdvsDxa6UfbfP9AoAAP//nEnN5vQAAAA=`
)
